name: SCHEDULED

on:
  schedule:
    - cron:  '6 * * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Nuget Restore
      run: nuget restore -Verbosity quiet

    - name: Setup-MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      id: build
      run: |
        msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: trxer-console
        path: ${{ github.workspace }}\TrxerConsole\bin\Release\TrxerConsole.exe
        retention-days: 90
